### ISSUE TITLE
可以支持自定义字体吗?

### ISSUE THREAD

**Issue by nbchen** [MaxChang3/hexo-markmap#28]
因为发现现在主题的字体对这个渲染不起作用。
=> 可以在配置里自定义字体吗？
比如
```yaml
font:
  xmind:
    external: true
    family: Microsoft YaHei,sans-serif
``` 
现在的
  - RPC
    - [<font face="Consolas">NIO</font>](xxxxlinksxxxxx) 
{% endmarkmap %}
可以达到效果,但是感觉不太灵活

**Comment by MaxChang3** [comment]
我直接在元素上加 css 不管用，好奇怪。但是 markmap 官网的是可以的。我晚上再试试，可以的话我加个开关。

**Comment by MaxChang3** [comment]
尝试添加了一下
```css
.markmap-container div{
      font: 300 16px/20px Consolas; /* 根据原始 css 改的 */
}
```
或者
```css
.markmap-container div{
      font-family: Consolas;
}
```
都会导致字体溢出，你那边会出现这种情况么？
我再研究一下。
