### ISSUE TITLE
pjax config structure is different in different themes

### ISSUE THREAD

**Issue by MaxChang3** [MaxChang3/hexo-markmap#34]
for [hexo-theme-next](https://github.com/next-theme/hexo-theme-next)
```yaml
pjax: false
```
for [hexo-theme-butterfly](https://github.com/jerryc127/hexo-theme-butterfly)
```yaml
pjax:
  enable: false
  exclude:
    # - xxxx
    # - xxxx
```
this might cause problems using just a single option `theme_config.pjax` to detective whether pjax is turned on in theme config
