### ISSUE TITLE
npm install hexo-markmap 无法安装

### ISSUE THREAD

**Issue by android1122** [maxchang3/hexo-markmap#49]
我用了GitHub的action进行部署：
```
jobs:
  pages:
    runs-on: ubuntu-latest #使用的系统
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3 #调用官方的脚本，直接复制我们的项目文件到系统 
      - name: 安装node
        uses: actions/setup-node@v2 #安装node环境
        with:
          node-version: "18"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: |
          npm install
          npm install hexo-markmap
          npm install hexo-theme-next
          npm install hexo-word-counter
          npm install hexo-related-posts
          npm install hexo-generator-searchdb
```
每次执行到 安装Install Dependencies时候，都会报错
```
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated cuid@[2](https://github.com/android1122/07blog/actions/runs/5373061572/jobs/9747067041#step:4:2).1.8: Cuid and other k-sortable and non-cryptographic ids (Ulid, ObjectId, KSUID, all UUIDs) are all insecure. Use @paralleldrive/cuid2 instead.
added 247 packages, and audited 248 packages in 10s
26 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
added 1 package, and audited 249 packages in 908ms
26 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
added 1 package, and audited 250 packages in 1s
26 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
added 2 packages, and audited 252 packages in 3s
26 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
added 9 packages, and audited 261 packages in 3s
[29](https://github.com/android1122/07blog/actions/runs/5373061572/jobs/9747067041#step:4:29) packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
added 1 package, and audited 262 packages in 7[30](https://github.com/android1122/07blog/actions/runs/5373061572/jobs/9747067041#step:4:30)ms
29 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
```
到了后面build之后就会出现：
```
Run npm run build
> hexo-site@0.0.0 build
> hexo generate
INFO  Validating config
ERROR Plugin load failed: hexo-markmap
Error: Cannot find module 'markmap-lib'
Require stack:
- /home/runner/work/07blog/07blog/node_modules/hexo-markmap/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:107[5](https://github.com/android1122/07blog/actions/runs/5373061572/jobs/9747067041#step:5:6):15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at req (/home/runner/work/07blog/07blog/node_modules/hexo/lib/hexo/index.js:292:23)
    at /home/runner/work/07blog/07blog/node_modules/hexo-markmap/index.js:1:90
    at /home/runner/work/07blog/07blog/node_modules/hexo/lib/hexo/index.js:305:14
    at tryCatcher (/home/runner/work/07blog/07blog/node_modules/bluebird/js/release/util.js:1[6](https://github.com/android1122/07blog/actions/runs/5373061572/jobs/9747067041#step:5:7):23)
    at Promise._settlePromiseFromHandler (/home/runner/work/07blog/07blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/work/07blog/07blog/node_modules/bluebird/js/release/promise.js:604:1[8](https://github.com/android1122/07blog/actions/runs/5373061572/jobs/9747067041#step:5:9))
    at Promise._settlePromise0 (/home/runner/work/07blog/07blog/node_modules/bluebird/js/release/promise.js:64[9](https://github.com/android1122/07blog/actions/runs/5373061572/jobs/9747067041#step:5:10):[10](https://github.com/android1122/07blog/actions/runs/5373061572/jobs/9747067041#step:5:11))
    at Promise._settlePromises (/home/runner/work/07blog/07blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/runner/work/07blog/07blog/node_modules/bluebird/js/release/async.js:93:[12](https://github.com/android1122/07blog/actions/runs/5373061572/jobs/9747067041#step:5:13))
    at _drainQueue (/home/runner/work/07blog/07blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/work/07blog/07blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/home/runner/work/07blog/07blog/node_modules/bluebird/js/release/async.js:15:[14](https://github.com/android1122/07blog/actions/runs/5373061572/jobs/9747067041#step:5:15))
    at process.processImmediate (node:internal/timers:476:[21](https://github.com/android1122/07blog/actions/runs/5373061572/jobs/9747067041#step:5:22))
```
这个是插件的依赖已经被弃用了导致的吧。大佬有解决方案么？
