### ISSUE TITLE
新版运行报错 markmap.js:34 Uncaught SyntaxError: Unexpected token ':' (at markmap.js:34:14)

### ISSUE THREAD

**Issue by appotry** [maxchang3/hexo-markmap#50]
参数配置如下

```yaml
hexo_markmap:
  pjax: false
  katex: true
  prism: true # true | false
  userCDN:
    d3_js: https://fastly.jsdelivr.net/npm/d3@6
    markmap_view_js: https://fastly.jsdelivr.net/npm/markmap-view@0.2.7
    katex_css: 'https://fastly.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css'
    # prism_css: https://fastly.jsdelivr.net/npm/prismjs@1.25.0/themes/prism.css
    prism_css: 'https://blog.17lai.site/libs/prism/prism.min.css'
  lockView: false
  fixSVGAttrNaN: false
```

用AI助手查了下，AI的回复如下

这个错误是因为在第34行的 CDN 对象定义中的 css 属性赋值有语法错误:

```js
"css": [
  https://fastly.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css
  https://blog.17lai.site/libs/prism/prism.min.css 
]
```

数组元素之间使用的是冒号 ":",而不是逗号 ","。

应该修改为:

```js
"css": [
  "https://fastly.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css",
  "https://blog.17lai.site/libs/prism/prism.min.css"
]
```

使用逗号分隔数组元素,并添加引号将地址作为字符串。

这是一个典型的 JavaScript 语法错误,应该仔细检查对象字面量中的属性定义,确保使用了正确的语法。
